### ISSUE TITLE
Json files

### ISSUE THREAD

**Issue by dsakura** [patrickkfkan/patreon-dl#9]
Sorry, here I'm again.
The format of the files I downloaded is json, but with the tool, they downloaded as txt. Is there something in the configuration that I can change to resolve this?

Many thanks!

**Comment by patrickkfkan** [comment]
Hi, would it be possible to provide a link to an example post?

**Comment by dsakura** [comment]
sure!
https://www.patreon.com/posts/summon-97004610

**Comment by patrickkfkan** [comment]
I have just published v1.2.2. Could you check if this version fixes the issue? I did not verify against the link you gave me because it's patron-only. Thanks.

**Comment by dsakura** [comment]
It didn't solve it, I created a script to rename the files, it's not difficult to deal with. If it's difficult to resolve, that's okay. No big problem. Many thanks!

**Comment by patrickkfkan** [comment]
Hi, please test v1.3.0.

 I subscribed to the creator of the post that you linked for the sake of testing this.  The issue should be resolved in this version. Let me know if it works for you too (maybe test by downloading a single post in a new directory so you can be sure no cache is being used).

**Comment by dsakura** [comment]
Nice many thanks! Soon I'll test it!
